add hci_ext_per command
acburigo/python-hci pull request #30
Opened 2017-12-18 19:43 UTC by hoarf

2017-12-18 19:56 UTC, acburigo requested changes
You need to add your command to autocast and init.

Please, refer to any pull request adding a new command so you have an idea of how to add a new command to this library.

2017-12-18 19:56 UTC, acburigo commented on hci/command/commands/hci_ext_per.py
> +class HCI_EX_PER(CommandPacket):
The class name is given by the `TI_BLE_Vendor_Specific_HCI_Guide.pdf` file.

2017-12-19 11:19 UTC, hoarf commented
I made the requested changes, please review it again.

2017-12-19 14:51 UTC, acburigo requested changes

2017-12-19 14:51 UTC, acburigo commented on hci/command/commands/__init__.py
> +from .hci_packet_error_rate_cmd import HCI_EXT_PacketErrorRateCmd
You can remove `cmd` from the file name and `Cmd` from the class name.

2017-12-19 14:51 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate_cmd.py
> +class HCI_EXT_PacketErrorRateCmd(CommandPacket):
You can remove `cmd` from the file name and `Cmd` from the class name.

2017-12-19 14:51 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate_cmd.py
> +from enum import IntEnum
`enum` should be imported with the top group of imports.
First group contains python modules, second group contains project modules.

2017-12-19 14:51 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate_cmd.py
> +            CommandPacket.OpCode.HCI_EX_PER,
This OpCode does not exist. Please, test your command before sending a pull request. You can test it the same way we show on our README.md example.

2017-12-19 14:51 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate_cmd.py
> +        return unpack('<H', data)[0]
`command` parameter is a single octet, so `SIZE_OCTETS = 1` and `unpack('<B', data)[0]`.

2017-12-19 14:51 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate_cmd.py
> +            int(self.command),
Translate `command` using the `enum` you created.
For example: `HCI_EXT_PacketErrorRateCmd.Command(self.command).name`

2017-12-19 14:51 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate_cmd.py
> +        )
File ends with a new line character.

2017-12-19 15:37 UTC, hoarf commented
all changes requested were made and the pr is passing the test describing in the readme

2017-12-19 15:53 UTC, acburigo requested changes

2017-12-19 15:53 UTC, acburigo commented on hci/command/commands/__init__.py
> +from .hci_ext_packet_error_rate import HCI_EXT_PacketErrorRate
This is listed in alphabetic order.

2017-12-19 15:53 UTC, acburigo commented on hci/command/autocast.py
>      }
Same order as `__init__.py`.

2017-12-19 15:53 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate.py
> +        return pack('<HH', conn_handle, client_rx_mtu)
`<HB`

2017-12-19 15:53 UTC, acburigo commented on hci/command/commands/hci_ext_packet_error_rate.py
> +            HCI_EXT_PacketErrorRate.Command(self.command).value,
First, comes the hexadecimal value, then comes the name (between parenthesis). Check other commands if you are in doubt.

2017-12-19 16:02 UTC, hoarf commented
fixed the ordering, the 'HH' issue and the packet name

2017-12-19 16:05 UTC, acburigo approved these changes

2017-12-19 16:05 UTC, merged